#!/usr/bin/env python3
"""Generate src/unicode_tables.h from Python's Unicode database.

The llama-bpe pre-tokenizer pattern uses \\p{L}, \\p{N} and \\s. POSIX regex
has no Unicode property classes, so the pre-tokenizer is hand-written and needs
its own classification tables. Generating them beats hand-typing ranges and
makes the result reproducible and auditable.

    python3 tools/gen_unicode_tables.py > src/unicode_tables.h
"""
import sys
import unicodedata

MAX_CP = 0x110000


def ranges_for(pred):
    """Collapse the codepoints satisfying pred into (lo, hi) inclusive ranges."""
    out, start, prev = [], None, None
    for cp in range(MAX_CP):
        if pred(cp):
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out


def cat(cp):
    return unicodedata.category(chr(cp))


# \p{L} — Lu Ll Lt Lm Lo.  \p{N} — Nd Nl No.
is_letter = lambda cp: cat(cp)[0] == "L"
is_number = lambda cp: cat(cp)[0] == "N"

# \s — Unicode whitespace. Zs plus the ASCII controls regex engines treat as
# whitespace, plus the line/paragraph separators.
WS_EXTRA = {0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x1C, 0x1D, 0x1E, 0x1F, 0x85}
is_space = lambda cp: cat(cp) in ("Zs", "Zl", "Zp") or cp in WS_EXTRA


def emit(name, rs):
    print(f"/* {len(rs)} ranges */")
    print(f"static const uc_range_t {name}[] = {{")
    for i in range(0, len(rs), 4):
        row = "".join(f" {{0x{lo:05X},0x{hi:05X}}}," for lo, hi in rs[i:i + 4])
        print("   " + row)
    print("};")
    print(f"#define {name.upper()}_N ((int)(sizeof {name} / sizeof {name}[0]))")
    print()


def main():
    L, N, S = ranges_for(is_letter), ranges_for(is_number), ranges_for(is_space)
    print("/* GENERATED by tools/gen_unicode_tables.py — do not edit by hand.")
    print(f" * Python {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}.")
    print(" * Regenerate with: python3 tools/gen_unicode_tables.py > src/unicode_tables.h")
    print(" */")
    print("#ifndef TC_UNICODE_TABLES_H")
    print("#define TC_UNICODE_TABLES_H")
    print()
    print("typedef struct { unsigned int lo, hi; } uc_range_t;")
    print()
    emit("uc_letter", L)
    emit("uc_number", N)
    emit("uc_space", S)
    print("#endif /* TC_UNICODE_TABLES_H */")
    ltot = sum(h - l + 1 for l, h in L)
    ntot = sum(h - l + 1 for l, h in N)
    print(f"/* letters: {ltot} codepoints, numbers: {ntot} */")


main()
